// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/IFMSChart.tsx": () => import("../components/mockups/IFMSChart.tsx"),
  "./components/mockups/IFMSLookup.tsx": () => import("../components/mockups/IFMSLookup.tsx"),
  "./components/mockups/IFMSPrintGuide.tsx": () => import("../components/mockups/IFMSPrintGuide.tsx"),
  "./components/mockups/WAMChart.tsx": () => import("../components/mockups/WAMChart.tsx")
};
